"""Alembic environment.

Two things differ from the generated default, both on purpose.

**The URL comes from settings, not from alembic.ini.** A connection string in a tracked file
is a credential in version control, and it makes the same command mean different databases
depending on which checkout you are in. Reading `DATABASE_URL` through the app's own
settings means migrations target exactly the database the app does.

**`compare_type` is on.** Without it, a column whose type changed produces an empty
autogenerated migration — the most expensive kind, because it looks like there was nothing
to do.

**The version table is renamed.** MLflow keeps its backend store in this same database and
migrates it with Alembic too, under the default `alembic_version`. Sharing that table means
each project reads the other's revision as its own: the first `alembic upgrade` here would
have found MLflow's `acf3f17fdcc7`, which is in no chain of ours, and either failed outright
or overwritten the row MLflow needs to know its own schema version. Two Alembic-managed
schemas in one database need two version tables.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from gridsense.config import get_settings
from gridsense.db import ALEMBIC_VERSION_TABLE, is_owned_table, metadata

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = metadata


def _include_object(obj, name: str, type_: str, reflected: bool, compare_to) -> bool:
    """Alembic hook: restrict autogenerate to tables this application declares.

    Only tables are filtered — columns and indexes are still compared normally, or a column
    added to one of our own tables would go unnoticed.
    """
    return is_owned_table(name) if type_ == "table" else True


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a connection — for review, or a DBA-applied change."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        version_table=ALEMBIC_VERSION_TABLE,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            version_table=ALEMBIC_VERSION_TABLE,
            # MLflow's tables live in this database too. Without this, autogenerate would
            # propose dropping every one of them as "not in the metadata".
            include_object=_include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
