"""The database tables this application owns, defined once.

Before this module the schema had no single definition. `degrade_predictions` was created by
a `CREATE TABLE IF NOT EXISTS` executed on every prediction, which is fine until the first
column change: `IF NOT EXISTS` does nothing to a table that already exists with the old
shape, so the DDL and the reality diverge silently and the next INSERT fails on a column
that the code believes it created.

The metadata below is the source of truth, and it has exactly two consumers:

- **Alembic** autogenerates migrations by diffing this against the live database, so a
  column added here produces a migration rather than a surprise.
- **`create_all`**, for local development and the integration tests, where running a
  migration chain to get one table is friction with no payoff.

Both build the same table from the same definition, and `tests/test_migrations.py` asserts
that the migration chain and this metadata agree — which is the check that stops the two
consumers drifting apart, since nothing else would notice.

**What is deliberately not here.** `degrade_samples` is written by
`DataFrame.to_sql(if_exists="replace")`: a seed dataset replaced wholesale, not a schema
that migrates, and putting it under Alembic would mean migrating a table whose shape is
whatever the last seed produced. The pgvector tables belong to `langchain-postgres`, which
manages its own schema; adopting them here would fork a library's internals.
"""

from __future__ import annotations

from sqlalchemy import Column, DateTime, Float, Integer, MetaData, Table, Text, func

#: Explicit naming convention so autogenerated constraint names are stable and reversible.
#: Without it Alembic emits `op.drop_constraint(None, ...)` for anything the database named
#: itself, and the downgrade fails at exactly the moment it is needed.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)

PREDICTIONS_TABLE = "degrade_predictions"

#: Every `/predict` call, kept so drift can be measured against the training distribution
#: later (:mod:`gridsense.degrade.monitor`). Nullable feature columns on purpose: this is an
#: observation log, and a row that records what was actually received — including a gap — is
#: worth more than a rejected insert that records nothing.
predictions = Table(
    PREDICTIONS_TABLE,
    metadata,
    Column("id", Integer, primary_key=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("cycle_count", Float),
    Column("avg_temperature_c", Float),
    Column("avg_dod", Float),
    Column("avg_c_rate", Float),
    Column("calendar_age_days", Float),
    Column("predicted_soh", Float),
    Column("model_version", Text),
)


#: Alembic's bookkeeping table. **Not** the default `alembic_version`: MLflow keeps its
#: backend store in this same database and migrates it with Alembic too, under that name.
#: Sharing the table would make each project read the other's revision as its own — the
#: first `alembic upgrade` here would find MLflow's revision, which belongs to no chain of
#: ours, and either fail outright or overwrite the row MLflow needs to know its own version.
#: Two Alembic-managed schemas in one database need two version tables.
ALEMBIC_VERSION_TABLE = "gridsense_alembic_version"


def is_owned_table(name: str) -> bool:
    """Whether ``name`` is a table this application declares.

    Used by Alembic's ``include_object`` to keep autogenerate to our own tables. Without it,
    a database shared with MLflow and with ``langchain-postgres``' pgvector tables makes
    every foreign table look like something to drop, and ``--autogenerate`` cheerfully
    proposes a migration that deletes the experiment tracking store.
    """
    return name in metadata.tables
